[package]
name = "polars-doc-examples"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Code examples included in the Polars documentation website"

[dependencies]
chrono = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
aws-config = { version = "0.57" }
aws-sdk-s3 = { version = "0.35" }

[dependencies.polars]
workspace = true

[[bin]]
name = "home"
path = "home/example.rs"
required-features = ["polars/lazy"]

[[bin]]
name = "user-guide-basics-expressions"
path = "user-guide/basics/expressions.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-basics-joins"
path = "user-guide/basics/joins.rs"
[[bin]]
name = "user-guide-basics-reading-writing"
path = "user-guide/basics/reading-writing.rs"
required-features = ["polars/json"]
[[bin]]
name = "user-guide-basics-series-dataframes"
path = "user-guide/basics/series-dataframes.rs"
required-features = ["polars/describe"]

[[bin]]
name = "user-guide-concepts-contexts"
path = "user-guide/concepts/contexts.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-concepts-expressions"
path = "user-guide/concepts/expressions.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-concepts-lazy-vs-eager"
path = "user-guide/concepts/lazy-vs-eager.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-concepts-streaming"
path = "user-guide/concepts/streaming.rs"
required-features = ["polars/lazy"]

[[bin]]
name = "user-guide-io-cloud-storage"
path = "user-guide/io/cloud-storage.rs"
required-features = ["polars/csv"]


