[package]
name = "polars-doc-examples"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Code examples included in the Polars documentation website"

[dependencies]
chrono = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
aws-config = { version = "0.57" }
aws-sdk-s3 = { version = "0.35" }

[dependencies.polars]
workspace = true

[[bin]]
name = "home"
path = "home/example.rs"
required-features = ["polars/lazy"]

[[bin]]
name = "user-guide-basics-expressions"
path = "user-guide/basics/expressions.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-basics-joins"
path = "user-guide/basics/joins.rs"
[[bin]]
name = "user-guide-basics-reading-writing"
path = "user-guide/basics/reading-writing.rs"
required-features = ["polars/json"]
[[bin]]
name = "user-guide-basics-series-dataframes"
path = "user-guide/basics/series-dataframes.rs"
required-features = ["polars/describe"]

[[bin]]
name = "user-guide-concepts-contexts"
path = "user-guide/concepts/contexts.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-concepts-expressions"
path = "user-guide/concepts/expressions.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-concepts-lazy-vs-eager"
path = "user-guide/concepts/lazy-vs-eager.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-concepts-streaming"
path = "user-guide/concepts/streaming.rs"
required-features = ["polars/lazy"]

[[bin]]
name = "user-guide-io-cloud-storage"
path = "user-guide/io/cloud-storage.rs"
required-features = ["polars/csv"]
[[bin]]
name = "user-guide-io-csv"
path = "user-guide/io/csv.rs"
required-features = ["polars/csv"]
[[bin]]
name = "user-guide-io-json"
path = "user-guide/io/json.rs"
required-features = ["polars/json"]
[[bin]]
name = "user-guide-io-parquet"
path = "user-guide/io/parquet.rs"
required-features = ["polars/parquet"]

[[bin]]
name = "user-guide-transformations-concatenation"
path = "user-guide/transformations/concatenation.rs"
required-features = ["polars/lazy"]
# [[bin]]
# name = "user-guide-transformations-joins"
# path = "user-guide/transformations/joins.rs"
# required-features = ["polars/lazy", "polars/asof_join"]
[[bin]]
name = "user-guide-transformations-melt"
path = "user-guide/transformations/melt.rs"
[[bin]]
name = "user-guide-transformations-pivot"
path = "user-guide/transformations/pivot.rs"
required-features = ["polars/lazy"]

[[bin]]
name = "user-guide-transformations-time-series-filter"
path = "user-guide/transformations/time-series/filter.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-transformations-time-series-parsing"
path = "user-guide/transformations/time-series/parsing.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-transformations-time-series-resampling"
path = "user-guide/transformations/time-series/resampling.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-transformations-time-series-rolling"
path = "user-guide/transformations/time-series/rolling.rs"
required-features = ["polars/lazy"]
[[bin]]
name = "user-guide-transformations-time-series-timezones"
path = "user-guide/transformations/time-series/timezones.rs"
required-features = ["polars/lazy"]
